# Generated by Django 5.2.3 on 2025-06-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='contact',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='course',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('executive', 'Executive')], default='student', max_length=20),
        ),
    ]
