# Generated by Django 5.2.3 on 2025-06-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_waitlistentry_contact_waitlistentry_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
